version: '3.4'

services:
  api:
    image: ${DOCKER_IMAGE:-it.bz.noi.community-api}:${DOCKER_TAG:-latest}
    build:
      context: /
      dockerfile: /Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      SERVICE_SCOPE: ${SERVICE_SCOPE}
      SERVICE_URL: ${SERVICE_URL}
      TENANT_ID: ${TENANT_ID}
    ports:
      - "60209:80"
